# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 597)
        MainWindow.setStyleSheet("/*Styles for the info_frame element*/\n"
"#info_frame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/*Styles for the labels, input fields and combox boxes inside the \"info_frame\" */\n"
"#info_frame QLabel,\n"
"#info_frame QLineEdit,\n"
"#info_frame QComboBox,\n"
"#function_frame QPushButton,\n"
"QHeaderView::section {\n"
"    font-family: Segoe UI Semibold;\n"
"    font-size 12px;\n"
"}\n"
"\n"
"/*Styles for input fields and combo boxes inside info_frame*/\n"
"#info_frame QLineEdit,\n"
"#info_frame QComboBox {\n"
"    padding: 4px 5px;\n"
"    border: 1px solid #838383;\n"
"    border-radius: 2px\n"
"}\n"
"\n"
"/*Focus styles for input fields and combo boxes*/\n"
"#info_frame QLineEdit:focus,\n"
"#info_frame QComboBox:focus{\n"
"    border-color: #0055ff;\n"
"}\n"
"\n"
"/*Styles for combox boxes drop-down*/\n"
"QComboBox::drop-down {\n"
"    background: transparent;\n"
"    border: none;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"/*Styles for the down-arrow icon in combo boxes*/\n"
"QComboBox::down-arrow {\n"
"    image: url(:./icons/expand_more.png);\n"
"}\n"
"\n"
"/*Style for \'result_frame\'*/\n"
"#result_frame {\n"
"    border-radius: 5px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"/*Style for border of QtableWidget*/\n"
"QTableWidget {\n"
"    border-radius: 3px;\n"
"    border: 1px solid #f0f0f0;\n"
"}\n"
"\n"
"/*Style for table header section */\n"
"QHeaderView::section {\n"
"border: none;\n"
"border-bottom: 1px solid #d0c6ff;\n"
"text-align: left;\n"
"padding: 3px 5px;\n"
"}\n"
"\n"
"/*Styles for table items */\n"
"QTableWidget::Item {\n"
"    border-bottom: 1px solid #d0c6ff;\n"
"    color: #000;\n"
"    padding-left: 3px;\n"
"}\n"
"\n"
"/*Styles for buttons inside the \'function_frame\'*/\n"
"#function_frame QPushButton {\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #f0f0f0;\n"
"    border-radius: 5px;\n"
"    background-color: #84e8f7;\n"
"}\n"
"\n"
"/*Style for delete_btn*/\n"
"#function_frame #delete_btn {\n"
"    background-color: #ff8183;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tite_label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Script MT Bold")
        font.setPointSize(30)
        self.tite_label.setFont(font)
        self.tite_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tite_label.setObjectName("tite_label")
        self.gridLayout_6.addWidget(self.tite_label, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame, 0, 0, 1, 1)
        self.info_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.info_frame.setStyleSheet("info_frame {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.info_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.info_frame.setObjectName("info_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.info_frame)
        self.gridLayout_3.setContentsMargins(30, 20, 30, 20)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(13)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.info_frame)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.info_frame)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.info_frame, 1, 0, 1, 1)
        self.function_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.function_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.function_frame.setObjectName("function_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.function_frame)
        self.gridLayout_4.setContentsMargins(30, 10, 30, 10)
        self.gridLayout_4.setVerticalSpacing(13)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.add_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Users/GODSON/Desktop/Images_2/Icons/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_btn.setIcon(icon)
        self.add_btn.setIconSize(QtCore.QSize(16, 16))
        self.add_btn.setObjectName("add_btn")
        self.gridLayout_4.addWidget(self.add_btn, 0, 0, 1, 1)
        self.update_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../Users/GODSON/Desktop/Images_2/Icons/update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.update_btn.setIcon(icon1)
        self.update_btn.setObjectName("update_btn")
        self.gridLayout_4.addWidget(self.update_btn, 0, 1, 1, 1)
        self.select_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../Users/GODSON/Desktop/Images_2/Icons/select.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_btn.setIcon(icon2)
        self.select_btn.setObjectName("select_btn")
        self.gridLayout_4.addWidget(self.select_btn, 0, 2, 1, 1)
        self.search_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../Users/GODSON/Desktop/Images_2/Icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_btn.setIcon(icon3)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout_4.addWidget(self.search_btn, 0, 3, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../Users/GODSON/Desktop/Images_2/Icons/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_btn.setIcon(icon4)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout_4.addWidget(self.clear_btn, 0, 4, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(parent=self.function_frame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../Users/GODSON/Desktop/Images_2/Icons/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_btn.setIcon(icon5)
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout_4.addWidget(self.delete_btn, 0, 5, 1, 1)
        self.gridLayout_7.addWidget(self.function_frame, 2, 0, 1, 1)
        self.result_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.result_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.result_frame.setObjectName("result_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.result_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.result_frame)
        self.tableWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.result_frame, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tite_label.setText(_translate("MainWindow", "Students Information System"))
        self.label_2.setText(_translate("MainWindow", "Student ID"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Last Name"))
        self.label_5.setText(_translate("MainWindow", "State"))
        self.label_6.setText(_translate("MainWindow", "City"))
        self.label_7.setText(_translate("MainWindow", "Email Address"))
        self.add_btn.setText(_translate("MainWindow", "Add"))
        self.update_btn.setText(_translate("MainWindow", "Update"))
        self.select_btn.setText(_translate("MainWindow", "Select"))
        self.search_btn.setText(_translate("MainWindow", "Search"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.delete_btn.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Student ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "City"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Email Address"))
